version: '2'
services:
    projetjhipster2h2-app:
        image: projetjhipster2h2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://projetjhipster2h2-postgresql:5432/ProjetJHipster2H2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projetjhipster2h2-postgresql:
        extends:
            file: postgresql.yml
            service: projetjhipster2h2-postgresql
