version: '2'
services:
    jhipsterdemo-app:
        image: jhipsterdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterdemo-postgresql:5432/JhipsterDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterdemo-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterdemo-postgresql
